"use client";

import { motion } from "framer-motion";
import { Download, Share2, FileText } from "lucide-react";
import { generatePDFReport } from "./PDFReportGenerator";

interface ExportReportProps {
  predictions: any[];
  condition: string;
  probability: number;
  riskTier: string;
  contributingFactors: any[];
  explanation: string;
  adaptiveScore?: any;
  recommendations?: any[];
  sceneImage?: string;
}

export default function ExportReport({
  predictions,
  condition,
  probability,
  riskTier,
  contributingFactors,
  explanation,
  adaptiveScore,
  recommendations,
  sceneImage,
}: ExportReportProps) {
  const handleDownloadPDF = () => {
    generatePDFReport({
      predictions,
      condition,
      probability,
      riskTier,
      contributingFactors,
      explanation,
      healthScore: adaptiveScore?.health_score,
      adaptiveScore,
      recommendations,
      redFlags: adaptiveScore?.detected_red_flags,
      sceneImage,
    });
  };

  const handleShare = async () => {
    const shareText = `AetherDx AI Health Report\n\nPrimary Risk: ${condition} (${probability}%)\nRisk Level: ${riskTier}\nHealth Score: ${Math.round(100 - probability)}/100\n\nGenerated by AetherDx AI v2.0 — Predict Before You Feel`;
    
    if (navigator.share) {
      try {
        await navigator.share({ title: "AetherDx AI Health Report", text: shareText });
      } catch {}
    } else {
      await navigator.clipboard.writeText(shareText);
      alert("Report summary copied to clipboard!");
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 5 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 1.2 }}
      className="flex gap-2 mt-3"
    >
      <button
        onClick={handleDownloadPDF}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium
                   bg-[#6366F1]/10 border border-[#6366F1]/25 text-[#818CF8]
                   hover:bg-[#6366F1]/20 hover:border-[#6366F1]/40
                   transition-all duration-200"
        id="btn-export-pdf"
      >
        <FileText size={13} />
        Download PDF Report
      </button>
      <button
        onClick={handleShare}
        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium
                   bg-white/[0.03] border border-white/8 text-[#A0A0A0]
                   hover:bg-[#6366F1]/10 hover:border-[#6366F1]/30 hover:text-[#818CF8]
                   transition-all duration-200"
        id="btn-share"
      >
        <Share2 size={13} />
        Share
      </button>
    </motion.div>
  );
}
